import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: ROS 2',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-01-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Simulation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-02-simulation',
        },
      ],
    },
    {
        type: 'category',
        label: 'Module 3: NVIDIA Isaac',
        items: [
            {
                type: 'autogenerated',
                dirName: 'module-03-nvidia-isaac',
            },
        ],
    },
    {
        type: 'category',
        label: 'Module 4: Vla',
        items: [
            {
                type: 'autogenerated',
                dirName: 'module-04-vla',
            },
        ],
    },
  ],
};

export default sidebars;